name: ✨✨ Feature Request
description: File a feature request
title: "✨✨ <title>"
labels: [Enhancement, Triage]
body:


- type: checkboxes
  attributes:
    label: Is there an existing feature request that has already been created?
    description: Please search to see if a feature request already exists.
    options:
    - label: I have searched the exiting features requests
      required: true

- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: false

- type: textarea
  attributes:
    label: Describe the solution you would like?
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Alternative Solutions
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
