name: Bug on the Docker version 
description: File a bug/issue related to the docker-based implementation of SELKS
title: "🐞🐋 <title>"
labels: [Bug, Docker, Triage]
body:


- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false

- type: input
  id: docker-version
  attributes:
    label: Docker version
    description: Output of `docker -v `
    placeholder: ex. Docker version 20.10.10, build b485636
  validations:
    required: true

- type: input
  id: docker-compose-version
  attributes:
    label: Docker version
    description: Output of `docker-compose -v `
    placeholder: ex. docker-compose version 1.29.2, build 5becea4c
  validations:
    required: true

- type: input
  id: os-version
  attributes:
    label: OS Version
    description: Output of `lsb_release -d`
  validations:
    required: true

- type: textarea
  id: env-file
  attributes:
    label: Content of the environnement File
    description: Output of `cat SELKS/docker/.env`
  validations:
    required: true

- type: textarea
  id: selks-version
  attributes:
    label: Version of SELKS
    description: Output of `git log -1`
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false